apps/products/urls.py
from django.urls import path
from .views import add_product, product_list, product_details

app_name = "products"

urlpatterns = [
    path('add/', add_product, name="add_product"),
    path('', product_list, name="product_list"),
    path('<id>/', product_details, name="product_details"),
]

apps/products/models.py
from unicodedata import category
from django.db import models
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    title = models.CharField(_("Title"), max_length=150)
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

class Product(models.Model):
    title = models.CharField(_("Title"), max_length=250)
    price = models.FloatField(_("Price"))
    image = models.ImageField(_("Image"), upload_to="products", null=True, blank=True)
    category = models.ForeignKey(Category, verbose_name=_("Category"), on_delete=models.SET_NULL, null=True, blank=True) # Or Cascade

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return f'[{self.title}:{self.price}]'

apps/products/forms.py
from django import forms
from .models import Product
class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        # fields = ('title','price')
        exclude= ('id',)

apps/products/views.py
from django.shortcuts import redirect, render
from .forms import ProductForm
from .models import Product

def product_list(request):
    prds = Product.objects.all()
    context = {
        'products': prds
    }
    return render(request, 'products/list.html', context)

def product_details(request, id):
    prd = Product.objects.filter(id=id).first()
    context = {
        'product': prd
    }
    return render(request, 'products/details.html', context)
"""
d = {
    "title": 'titre',
    "object": {
        "attrs": [1,2,3,4,5,6],
        'other': {'hack': 'it'}
    }
}
d['object']['other']['hack']
d.get('object').get('other').get('hack')
"""
def add_product(request):
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(data=request.POST)
        if form.is_valid():
            print(request.POST)
            form.save()
            return redirect('products:product_list')
            """
            p = Product(
                title= request.POST.get('title'),
                price=request.POST['price']
            )
            """
        else:
            form = ProductForm(data=request.POST)
    context = {
        'form': form
    }
    return render(request, 'products/add.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ECommerce - {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/materia/bootstrap.min.css" integrity="sha384-B4morbeopVCSpzeC1c4nyV0d0cqvlSAfyXVfrPJa25im5p+yEN/YmhlgQP/OyMZD" crossorigin="anonymous">
</head>
<body>
    {% block content %}{% endblock content %}

    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US" dir="ltr">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- ===============================================-->
    <!--    Document Title-->
    <!-- ===============================================-->
    <title>majestic | Landing, Ecommerce &amp; Business Templatee</title>


    <!-- ===============================================-->
    <!--    Favicons-->
    <!-- ===============================================-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/img/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/img/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/img/favicons/favicon-16x16.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicons/favicon.ico' %}">
    <link rel="manifest" href="{% static 'assets/img/favicons/manifest.json' %}">
    <meta name="msapplication-TileImage" content="{% static 'assets/img/favicons/mstile-150x150.png' %}">
    <meta name="theme-color" content="#ffffff">


    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link href="{% static 'assets/css/theme.css' %}" rel="stylesheet" />

  </head>


  <body>

    <!-- ===============================================-->
    <!--    Main Content-->
    <!-- ===============================================-->
    <main class="main" id="top">
      {% include 'includes/navbar.html' %}
      {% include 'includes/first_section.html' %}


      <!-- ============================================-->
      <!-- <section> begin ============================-->
      {% include 'includes/second_section.html' %}
      <!-- <section> close ============================-->
      <!-- ============================================-->




      <!-- ============================================-->
      <!-- <section> begin ============================-->
     {% include 'includes/third_section.html' %}
      <!-- <section> close ============================-->
      <!-- ============================================-->




      <!-- ============================================-->
      <!-- <section> begin ============================-->
      {% include 'includes/section_four.html' %}
      <!-- <section> close ============================-->
      <!-- ============================================-->


      {% include 'includes/section_five.html' %}


      <!-- ============================================-->
      <!-- <section> begin ============================-->
      {% include 'includes/collections.html' %}
      <!-- <section> close ============================-->
      <!-- ============================================-->


     {% include 'includes/best_seller.html' %}


      <!-- ============================================-->
      <!-- <section> begin ============================-->
      {% include 'includes/outlet.html' %}
      <!-- <section> close ============================-->
      <!-- ============================================-->




      <!-- ============================================-->
      <!-- <section> begin ============================-->
      {% include 'includes/explore.html' %}
      <!-- <section> close ============================-->
      <!-- ============================================-->




      <!-- ============================================-->
      <!-- <section> begin ============================-->
      {% include 'includes/blog.html' %}
      
      <!-- <section> close ============================-->
      <!-- ============================================-->


      
        {% include 'includes/cta.html' %}

      <!-- ============================================-->
      <!-- <section> begin ============================-->
      {% include 'includes/footer.html' %}
      <!-- <section> close ============================-->
      <!-- ============================================-->


    </main>
    <!-- ===============================================-->
    <!--    End of Main Content-->
    <!-- ===============================================-->




    {% include 'includes/scripts.html' %}
  </body>
  

</html>

templates/includes/blog.html
{% load static %}
<section class="py-0 pb-8">

    <div class="container-fluid container-lg">
      <div class="row h-100 g-2 justify-content-center">
        <div class="col-sm-9 col-md-4 mb-3 mb-md-0 h-100">
          <div class="card card-span text-white h-100"><img class="img-card h-100" src="{% static 'assets/img/gallery/shoes-blog-1.png' %}" alt="..." />
            <div class="card-body px-xl-5 px-md-3 pt-0 pb-7">
              <div class="d-flex justify-content-between align-items-center bg-100 mt-n5 me-auto"><img src="{% static 'assets/img/gallery/author-1.png' %}" width="60" alt="..." />
                <div class="d-flex flex-1 justify-content-around"> <span class="text-900 text-center"><i data-feather="eye"> </i><span class="text-900 ms-2">35</span></span><span class="text-900 text-center"><i data-feather="heart"> </i><span class="text-900 ms-2">23</span></span><span class="text-900 text-center"><i data-feather="corner-up-right"> </i><span class="text-900 ms-2">14</span></span></div>
              </div>
              <h6 class="text-900 mt-3">Kelly Hudson . <span class="fw-normal">Fashion actiKelly Hudson . </span></h6>
              <h3 class="fw-bold text-1000 mt-5 text-truncate">How important are shoes in your style?</h3>
              <p class="text-900 mt-3">Is it possible to assess a person just on the basis of their footwear? Obviously, nobody should criticize, but certainly, shoes say a lot about someone. It matters for the outsiders that we meet every day...</p><a class="btn btn-lg text-900 fs-1 px-0 hvr-icon-forward" href="#!" role="button">Read more
                <svg class="bi bi-arrow-right-short hover-icon" xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"> </path>
                </svg></a>
            </div>
          </div>
        </div>
        <div class="col-sm-9 col-md-4 mb-3 mb-md-0 h-100">
          <div class="card card-span text-white h-100"><img class="img-card h-100" src="{% static 'assets/img/gallery/fashion-blog-2.png' %}" alt="..." />
            <div class="card-body px-xl-5 px-md-3 pt-0 pb-7">
              <div class="d-flex justify-content-between align-items-center bg-100 mt-n5 me-auto"><img src="{% static 'assets/img/gallery/author-2.png' %}" width="60" alt="..." />
                <div class="d-flex flex-1 justify-content-around"> <span class="text-900 text-center"><i data-feather="eye"> </i><span class="text-900 ms-2">35</span></span><span class="text-900 text-center"><i data-feather="heart"> </i><span class="text-900 ms-2">23</span></span><span class="text-900 text-center"><i data-feather="corner-up-right"> </i><span class="text-900 ms-2">14</span></span></div>
              </div>
              <h6 class="text-900 mt-3">Rotondwa Johnny . <span class="fw-normal">Fashion activist </span></h6>
              <h3 class="fw-bold text-1000 mt-5 text-truncate">Fashion trend forecast for Summer 2021</h3>
              <p class="text-900 mt-3">While the fashion industry has had a calm year, this season has seen some beautiful pieces. Over the previous several weeks, commanding coats, and elegant face masks have ruled Fashion Weeks...</p><a class="btn btn-lg text-900 fs-1 px-0 hvr-icon-forward" href="#!" role="button">Read more
                <svg class="bi bi-arrow-right-short hover-icon" xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"> </path>
                </svg></a>
            </div>
          </div>
        </div>
        <div class="col-sm-9 col-md-4 mb-3 mb-md-0 h-100">
          <div class="card card-span text-white h-100"><img class="img-card h-100" src="{% static 'assets/img/gallery/spring-dress-blog-3.png' %}" alt="..." />
            <div class="card-body px-xl-5 px-md-3 pt-0 pb-7">
              <div class="d-flex justify-content-between align-items-center bg-100 mt-n5 me-auto"><img src="{% static 'assets/img/gallery/author-3.png' %}" width="60" alt="..." />
                <div class="d-flex flex-1 justify-content-around"> <span class="text-900 text-center"><i data-feather="eye"> </i><span class="text-900 ms-2">35</span></span><span class="text-900 text-center"><i data-feather="heart"> </i><span class="text-900 ms-2">23</span></span><span class="text-900 text-center"><i data-feather="corner-up-right"> </i><span class="text-900 ms-2">14</span></span></div>
              </div>
              <h6 class="text-900 mt-3">Martin . <span class="fw-normal">Fashion activist </span></h6>
              <h3 class="fw-bold text-1000 mt-5 text-truncate">Spring exclusive collection for Men &amp; Women</h3>
              <p class="text-900 mt-3">Explore the first real-time photographic fashion magazine NOWFASHION to broadcast exclusive live fashion shows. Some of the most beautiful spring collection i want to share. See the....</p><a class="btn btn-lg text-900 fs-1 px-0 hvr-icon-forward" href="#!" role="button">Read more
                <svg class="bi bi-arrow-right-short hover-icon" xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"> </path>
                </svg></a>
            </div>
          </div>
        </div>
      </div>
    </div>
     <!-- end of .container-->

    </section>

templates/includes/collections.html
{% load static %}
<section class="py-0" id="collection">

    <div class="container">
      <div class="row h-100 gx-2">
        <div class="col-md-6">
          <div class="card card-span h-100 text-white"><img class="card-img h-100" src="{% static 'assets/img/gallery/urban.png' %}" alt="..." />
            <div class="card-img-overlay bg-dark-gradient">
              <div class="p-5 p-md-2 p-xl-5">
                <h1 class="fs-md-4 fs-lg-7 text-light">Urban Stories </h1>
                <h5 class="fs-2 text-light">collection</h5>
              </div>
            </div><a class="stretched-link" href="#!"></a>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card card-span h-100 text-white"><img class="card-img h-100" src="{% static 'assets/img/gallery/country.png' %}" alt="..." />
            <div class="card-img-overlay bg-dark-gradient">
              <div class="p-5 p-md-2 p-xl-5 d-flex flex-column flex-end-center align-items-baseline h-100">
                <h1 class="fs-md-4 fs-lg-7 text-light">Urban Stories </h1>
                <h5 class="fs-2 text-light">collection</h5>
              </div>
            </div><a class="stretched-link" href="#!"></a>
          </div>
        </div>
      </div>
    </div>
    <!-- end of .container-->

  </section>

templates/includes/cta.html
{% load static %}
<section class="py-11">
    <div class="bg-holder overlay overlay-0" style="background-image:url({% static 'assets/img/gallery/cta.png' %});background-position:center;background-size:cover;">
    </div>
    <!--/.bg-holder-->

    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="carousel slide carousel-fade" id="carouseCta" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active" data-bs-interval="10000">
                <div class="row h-100 align-items-center g-2">
                  <div class="col-12">
                    <div class="text-light text-center py-2">
                      <h5 class="display-4 fw-normal text-400 fw-normal mb-4">visit our Outlets in</h5>
                      <h1 class="display-1 text-white fw-normal mb-8">London</h1><a class="btn btn-lg text-light fs-1" href="#!" role="button">See Addresses
                        <svg class="bi bi-arrow-right-short" xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"> </path>
                        </svg></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="carousel-item" data-bs-interval="5000">
                <div class="row h-100 align-items-center g-2">
                  <div class="col-12">
                    <div class="text-light text-center py-2">
                      <h5 class="display-4 fw-normal text-400 fw-normal mb-4">visit our Outlets in</h5>
                      <h1 class="display-1 text-white fw-normal mb-8">Bristol</h1><a class="btn btn-lg text-light fs-1" href="#!" role="button">See Addresses
                        <svg class="bi bi-arrow-right-short" xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"> </path>
                        </svg></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="carousel-item" data-bs-interval="3000">
                <div class="row h-100 align-items-center g-2">
                  <div class="col-12">
                    <div class="text-light text-center py-2">
                      <h5 class="display-4 fw-normal text-400 fw-normal mb-4">visit our Outlets in</h5>
                      <h1 class="display-1 text-white fw-normal mb-8">Birmingham</h1><a class="btn btn-lg text-light fs-1" href="#!" role="button">See Addresses
                        <svg class="bi bi-arrow-right-short" xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"> </path>
                        </svg></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <button class="carousel-control-prev" type="button" data-bs-target="#carouseCta" data-bs-slide="prev"><span class="carousel-control-prev-icon" aria-hidden="true"></span><span class="visually-hidden">Previous</span></button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouseCta" data-bs-slide="next"><span class="carousel-control-next-icon" aria-hidden="true"></span><span class="visually-hidden">Next </span></button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

templates/includes/explore.html
{% load static %}
<section>

    <div class="container">
      <div class="row h-100 g-0">
        <div class="col-md-6">
          <div class="bg-300 p-4 h-100 d-flex flex-column justify-content-center">
            <h1 class="fw-semi-bold lh-sm fs-4 fs-lg-5 fs-xl-6">Gentle Formal Looks </h1>
            <p class="mb-5 fs-1">We provide the top formal apparel package to make your job look confident and comfortable. Stay connect.</p>
            <div class="d-grid gap-2 d-md-block"><a class="btn btn-lg btn-dark" href="#!" role="button">Explore Collection</a></div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card card-span h-100 text-white"><img class="card-img h-100" src="{% static 'assets/img/gallery/sharp-dress.png' %}" alt="..." /><a class="stretched-link" href="#!"></a></div>
        </div>
      </div>
    </div>
    <!-- end of .container-->

  </section>

templates/includes/first_section.html
{% load static %}
<section class="py-11 bg-light-gradient border-bottom border-white border-5">
    <div class="bg-holder overlay overlay-light" style="background-image:url({% static 'assets/img/gallery/header-bg.png' %});background-size:cover;">
    </div>
    <!--/.bg-holder-->

    <div class="container">
      <div class="row flex-center">
        <div class="col-12 mb-10">
          <div class="d-flex align-items-center flex-column">
            <h1 class="fw-normal"> With an outstanding style, only for you</h1>
            <h1 class="fs-4 fs-lg-8 fs-md-6 fw-bold">Exclusively designed for you</h1>
          </div>
        </div>
      </div>
    </div>
  </section>

templates/includes/footer.html
<section class="py-0 pt-7">

    <div class="container">
      <div class="row">
        <div class="col-6 col-lg-2 mb-3">
          <h5 class="lh-lg fw-bold text-1000">Company Info</h5>
          <ul class="list-unstyled mb-md-4 mb-lg-0">
            <li class="lh-lg"><a class="text-800 text-decoration-none" href="#!">About Us</a></li>
            <li class="lh-lg"><a class="text-800 text-decoration-none" href="#!">Affiliate</a></li>
            <li class="lh-lg"><a class="text-800 text-decoration-none" href="#!">Fashion Blogger</a></li>
          </ul>
        </div>
        <div class="col-6 col-lg-2 mb-3">
          <h5 class="lh-lg fw-bold text-1000">Help &amp; Support</h5>
          <ul class="list-unstyled mb-md-4 mb-lg-0">
            <li class="lh-lg"><a class="text-800 text-decoration-none" href="#!">Shipping Info</a></li>
            <li class="lh-lg"><a class="text-800 text-decoration-none" href="#!">Refunds</a></li>
            <li class="lh-lg"><a class="text-800 text-decoration-none" href="#!">How to Order</a></li>
            <li class="lh-lg"><a class="text-800 text-decoration-none" href="#!">How to Track</a></li>
            <li class="lh-lg"><a class="text-800 text-decoration-none" href="#!">Size Guides</a></li>
          </ul>
        </div>
        <div class="col-6 col-lg-2 mb-3">
          <h5 class="lh-lg fw-bold text-1000">Customer Care</h5>
          <ul class="list-unstyled mb-md-4 mb-lg-0">
            <li class="lh-lg"><a class="text-800 text-decoration-none" href="#!">Contact Us</a></li>
            <li class="lh-lg"><a class="text-800 text-decoration-none" href="#!">Payment Methods</a></li>
            <li class="lh-lg"><a class="text-800 text-decoration-none" href="#!">Bonus Point</a></li>
          </ul>
        </div>
        <div class="col-sm-6 col-lg-auto ms-auto">
          <h5 class="lh-lg fw-bold text-1000">Signup For The Latest News</h5>
          <div class="row input-group-icon mb-5">
            <div class="col-12">
              <input class="form-control input-box" type="email" placeholder="Enter Email" aria-label="email" />
              <svg class="bi bi-arrow-right-short input-box-icon" xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="#424242" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"> </path>
              </svg>
            </div>
          </div>
          <p class="text-800">
            <svg class="feather feather-phone me-3" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path>
            </svg><span class="text-800">+3930219390</span>
          </p>
          <p class="text-800">
            <svg class="feather feather-mail me-3" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path>
              <polyline points="22,6 12,13 2,6"></polyline>
            </svg><span class="text-800">something@gmail.com</span>
          </p>
        </div>
      </div>
      <div class="border-bottom border-3"></div>
      <div class="row flex-center my-3">
        <div class="col-md-6 order-1 order-md-0">
          <p class="my-2 text-1000 text-center text-md-start"> Made with&nbsp;
            <svg class="bi bi-suit-heart-fill" xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="#EB6453" viewBox="0 0 16 16">
              <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"></path>
            </svg>&nbsp;by&nbsp;<a class="text-800" href="https://themewagon.com/" target="_blank">ThemeWagon </a>
          </p>
        </div>
        <div class="col-md-6">
          <div class="text-center text-md-end"><a href="#!"><span class="me-4" data-feather="facebook"></span></a><a href="#!"> <span class="me-4" data-feather="instagram"></span></a><a href="#!"> <span class="me-4" data-feather="youtube"></span></a><a href="#!"> <span class="me-4" data-feather="twitter"></span></a></div>
        </div>
      </div>
    </div>
    <!-- end of .container-->

  </section>

templates/includes/scripts.html
{% load static %}
<!-- ===============================================-->
    <!--    JavaScripts-->
    <!-- ===============================================-->
    <script src="{% static 'vendors/@popperjs/popper.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendors/is/is.min.js' %}"></script>
    <script src="{% static 'https://polyfill.io/v3/polyfill.min.js?features=window.scroll' %}"></script>
    <script src="{% static 'vendors/feather-icons/feather.min.js' %}"></script>
    <script>
      feather.replace();
    </script>
    <script src="{% static 'assets/js/theme.js' %}"></script>

    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet">

templates/products/add.html
{% extends 'base.html' %}
{% block title %}Add Product{% endblock title %}
{% block content %}
<form method="POST" action="{% url 'products:add_product' %}">
    {% csrf_token %}
    {{form}}
    <button class="btn btn-primary" type="submit">Add Product</button>
</form>
{% endblock %}

templates/products/list.html
{% extends 'base.html' %}
{% block title %}Product List{% endblock title %}
{% block content %}
<a href="{% url 'products:add_product' %}">Add new product</a>
<ul class="list-group">
  {% for product in products %}
  <a href="{% url 'products:product_details' product.id %}">
    <li class="list-group-item d-flex justify-content-between align-items-center">
      {{product.title}}
      <span class="badge bg-primary rounded-pill">{{product.price}}</span>
    </li>
  </a>
  {% endfor %}
  </ul>
{% endblock content %}